### ISSUE TITLE
Autograder runs tests from student repository (which can also affect score)

### ISSUE THREAD

**Issue by EivindSt** [autograde/quickfeed#273]
In addition to running tests from the `tests` repo connected to some lab assignment, AG runs the tests in `<file>_test.go` from the student repository. This can cause some problems:

- Some tests might crash if the original test and the AG equivalent runs at the same time (this was observed e.g. with `TestWrite` in lab 3 for dat320-2020). If unfortunate, this could reduce the score of a correct solution.
- The AG output is cluttered with local tests which should not be there. Especially if students have made some tests of their own which happen to fail.
- Slight waste of resources.

Additionally, if the test from the student repo uses AG score objects, they can give themselves a higher score. While this would count as cheating, it does not make sense that students can write their own tests which affect their score.

Consider the following test (which was tested in lab 3 for dat320-2020):

```go
package lab3

import (
	"os"
	"testing"

	"github.com/autograde/aguis/kit/score"
)

func TestDummy(t *testing.T) {
	sc := score.NewScoreMax(100, 1)
	defer sc.WriteString(os.Stdout)
	defer sc.WriteJSON(os.Stdout)
	t.Error("dummy test failed")
	sc.DecBy(100)
}
```

First of all this test fails and shows up in the AG log. Additionally, the total score of the lab as well as the final score are affected by the `sc.DecBy(100)` operation. It also shows up in the "Test name" column in AG.

**Comment by meling** [comment]
This should be fixed by adding a `rm -rf *_test.go` in `go.tmpl` after cloning the student or group repo, but before copying the tests into the student's assignment directory structure. Actually, there is currently this line:

```sh
rm $(find ./ | grep _ag_test.go)
```

Which could be changed to:

```sh
rm $(find ./ | grep _test.go)
```

This should solve the problem. Will implement this soon.

**Comment by meling** [comment]
@EivindSt Can you please try to reproduce this with the currently deployed autograder server? (it should now be fixed)

**Comment by EivindSt** [comment]
@meling Seems to work as expected now.
