### ISSUE TITLE
Frontend: Set status dropdown menu is too cumbersome

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#282]
In the Results view, the `Status: ` and associated dropdown menu is too cumbersome to work with when we have many students to approve. I suggest two improvements: 

1. Just use plain buttons with color scheme indicating which is set along with changing the label as shown below:

  | Shortcut key:  | a | r | k | b |
  |--|--|--|--|--|
  | Default state: | Approve | Revision | Reject | Rebuild |
  | Pressed state: | Approved | Revising | Rejected | Rebuilding |

2. If possible, add keyboard shortcuts as indicated in the heading line of the table above.

Additional idea: it would be cool to be able to use keyboard to navigate the student/lab matrix as well, e.g. with the arrow keys. This would require some kind of marker to indicate which student/lab is currently selected. And it would require a space or enter key press to update the view.

**Comment by 0xf8f8ff** [comment]
Replaced with buttons and shortcuts.
