### ISSUE TITLE
Consider alternative structure of the different repos

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#289]
(cross-posting this issue here; was also posted in our private dat320 org... please leave your comments @0xf8f8ff @vinaysetty )

Currently, we have the following GitHub organization/repository structure (the last three columns list which entities has access to different repos):

|             | dat320 | dat320-YEAR | quickfeed | students | teachers |
|-------------|:------:|:-----------:|:---------:|:--------:|:--------:|
| course-info |    X   |      X      |           |     X    |     X    |
| assignments |    X   |      X      |     X     |     X    |     X    |
| solutions   |    X   |      X      |           |          |     X    |
| tests       |        |      X      |     X     |          |     X    |

Currently, we haven't added `tests` to dat320, and `assignments` aren't updated either. It is not clear that they are needed; it will just add another layer of complexity and stuff to synchronize.

Previously, we have had all four repositories available for the dat320-YEAR organization. However, it is not clear that it makes sense to maintain two versions of the `solutions` repo, if one is just a copy of the other.

Hence, we should at least implement the following structure, since `dat320/solutions` are now used to derive both `tests` and `assignments`.

|             | dat320 | dat320-YEAR | quickfeed | students | teachers |
|-------------|:------:|:-----------:|:---------:|:--------:|:--------:|
| course-info |    X   |      X      |           |     X    |     X    |
| assignments |        |      X      |     X     |     X    |     X    |
| solutions   |    X   |             |           |          |     X    |
| tests       |        |      X      |     X     |          |     X    |

In addition, we may consider to migrate also `dat320/course-info` into the `solutions` repo, and make a script that copies the relevant files from `solutions` to `dat320-YEAR/course-info`, allowing us to remove the `dat320/course-info` repo, giving us this structure:

|             | dat320 | dat320-YEAR | quickfeed | students | teachers |
|-------------|:------:|:-----------:|:---------:|:--------:|:--------:|
| course-info |        |      X      |           |     X    |     X    |
| assignments |        |      X      |     X     |     X    |     X    |
| solutions   |    X   |             |           |          |     X    |
| tests       |        |      X      |     X     |          |     X    |

In this way, we only need to maintain one repo in the `dat320` organization. With just one repo, we could rename the repo from `solutions` to `dat320`, with subdirectories for `course-info` and `solutions`. These could then form the basis for synchronizing to the `dat320-YEAR` repositories.

The scripts that handle this synchronization should add version tags, e.g. `dat320-2020-v1.0.0`.

# Not to be Adopted Idea

Another idea could be to also drop the `dat320-YEAR/course-info` repo, and integrate the relevant course information material in the `assignments` repo. The drawback with this approach is that the `assignments` repo is cloned by the students, making their repos cluttered with course-info material... So for now, I'm not too keen on this change.

**Comment by 0xf8f8ff** [comment]
Already fixed.
