### ISSUE TITLE
Student (and Teacher) View: Show delivered date without warning when already approved

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#323]
The delivered field shows the delivered date with a warning message if delivered after the deadline. This should be shown only when not already approved.

If an assignment has been approved before the deadline:
- show the last delivered date without the warning

If an assignment has been delivered after the deadline:
- show the warning message

We should show the delivered date when it was approved, in addition to the last delivered date.

![Screen Shot 2020-09-03 at 17 32 58](https://user-images.githubusercontent.com/810999/92232936-b0231c80-eeaf-11ea-8850-2e3dfbe0be33.png)

**Comment by 0xf8f8ff** [comment]
Note that assignment approved before deadline and submission delivered (re-delivered) after deadline might happen at the same time, as we allow rebuilding submissions after they have been approved. 
For now I set it to hide "days after deadline" warning completely on the student page (information about slip days seems to be sufficient) and after approval on the teacher page. Added a new line with the approved date to the info table as well. (#324)
