### ISSUE TITLE
Avoid that teachers gets subscribed to email notifications for the course (especially group activities)

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#350]
It is annoying that I get notifications on my GitHub associated email about course activity, as this can be quite massive. I think this is probably just me that gets this... I suspect that this is due to me approving groups, and for some reason I to become "member" of their groups on GitHub. 

@EivindSt I see that you have also approved a few groups. Did you get any emails related to those groups??

**Comment by 0xf8f8ff** [comment]
Yes, I also get notifications about push events to many (all?) of the student or group repos. Think it can only be changed in the organization settings, i.e., either on course creation or manually.

**Comment by EivindSt** [comment]
@meling As far as I can see I haven't received any emails related to student groups etc.

**Comment by meling** [comment]
This seems to have been fixed after following the instructions that I added to a new notifications section in [doc/teacher.md](https://github.com/autograde/quickfeed/blob/master/doc/teacher.md#notifications).
