### ISSUE TITLE
Quickfeed only works with master as default branch

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#351]
Quickfeed should support push to any default branch, even if named something other than `master`.

**Comment by nicro950** [comment]
https://github.com/autograde/quickfeed/blob/master/web/hooks/github.go#L55 This is the line

**Comment by nicro950** [comment]
the default branch name is part of the json request form the webhook, so this should be simple to implement. The field is called default_branch

**Comment by meling** [comment]
I guess it will be something like:

```golang
if payload.GetRef() != *payload.Repo.DefaultBranch {
```

Don't have time to test it now...
