### ISSUE TITLE
Student View: Show labs in same view with group annotation and sort by deadline

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#358]
Currently the student view shows `Group Labs` separate from other labs. Further, the list of labs are shown sorted by individual labs and then group labs. This is awkward when a later lab is individual. See attached screenshots.

- [ ] We should remove the `Group Labs` entry in the left-side menu. Instead, we could annotate the group labs with `(g)` after its name.
- [ ] Further, when showing the list of labs and their status (see screenshot), we should sort them by deadline and then name (if same deadline).
- [ ] Also, in the progress view, we should move the `Deadline: ` text to be above the date text (level with labX text), instead of to the left of the date. 

![Screen Shot 2020-10-24 at 19 38 50](https://user-images.githubusercontent.com/810999/97088374-9c36a400-1630-11eb-8bea-d81d50b0410d.png)
![Screen Shot 2020-10-24 at 19 38 56](https://user-images.githubusercontent.com/810999/97088378-a3f64880-1630-11eb-8bfe-95e9706ffbb0.png)

**Comment by meling** [comment]
Currently, in the teacher view, the `Group Results` menu item is disabled. We should remove this menu item and the corresponding code. 

@0xf8f8ff Are all the other items of this issue implemented? If so, we can close this issue when the menu item has been removed.

**Comment by 0xf8f8ff** [comment]
> Currently, in the teacher view, the `Group Results` menu item is disabled. We should remove this menu item and the corresponding code.
> 
> @0xf8f8ff Are all the other items of this issue implemented? If so, we can close this issue when the menu item has been removed.

The requested sorting is not implemented: labs are currently being sorted by  `Order` and this is the sole purpose of the `Order` field in the .yaml file.
