### ISSUE TITLE
Fix time.Parse layout constants

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#431]
We have several uses of such a `layout` const and strings with `2006-01-02T15:04:05`. These should be unified.

```golang
layout     = "2006-01-02T15:04:05"
```

**Comment by shoebsd31** [comment]
By unified what exactly do you mean, can you please provide an example ?

**Comment by meling** [comment]
I meant to say that we should use a single layout constant throughout the codebase, or at least most of the time. There might be cases where the time format is expected to be different. I didn't check all instances. The constant could be called `TimeLayout` and be located in a file `ag/consts.go`, where we might collect other "global" constants as well.
