### ISSUE TITLE
GetSubmissionsByCourse should only return the essentials

### ISSUE THREAD

**Issue by meling** [autograde/quickfeed#462]
We currently do the following in `getAllCourseSubmissions`:
```golang
	var getCourseSubFn func(uint64, pb.SubmissionsForCourseRequest_Type) ([]*pb.Assignment, error)
	if request.GetSkipBuildInfo() {
		getCourseSubFn = s.db.GetCourseAssignmentsWithSubmissionsNoBuildInfo
	} else {
		getCourseSubFn = s.db.GetCourseAssignmentsWithSubmissions
	}
	assignments, err := getCourseSubFn(request.GetCourseID(), request.Type)
	if err != nil {
		return nil, err
	}
```
And:
```golang
	if request.GetSkipBuildInfo() {
		sbm.BuildInfo = ""
		sbm.ScoreObjects = ""
	} else {
		err = sbm.MakeSubmissionReviews()
		if err != nil {
			return nil, err
		}
	}
```
Is the `GetSubmissionsByCourse` method also used in the frontend to fetch individual assignments/submission/score/build info??

Ideally, we should only use this method to get the data for the results view, without build info. Then fetch build info and scores when clicking individual links, or fetch them in the background, once the results view has been rendered.

**Comment by meling** [comment]
In fact, the `db.GetCourseAssignmentsWithSubmissionsNoBuildInfo` does return the build info, but doesn't return the manual review data. But the manual review data is probably empty if such data hasn't been submitted as part of a review. That is, I don't think we need to have two versions of this database call.

**Comment by oskargjolga** [comment]
I agree, and perhaps there should be a RPC to get a single submission by user/groupID, courseID, and assignmentID? At this point `getSubmissions` (which returns every submission by the user) has to be used to fetch individual submissions.

**Comment by meling** [comment]
Add test for this. Run test. Remove `SubmissionsForCourseRequest -> skipBuildInfo`. Rerun test.

**Comment by meling** [comment]
To avoid the `skipBuildInfo` field, we can use bitfield like below (see [this discussion](https://groups.google.com/g/protobuf/c/QnMnMzNpf1w))

```protobuf
message SubmissionsForCourseRequest {
    enum Type {
        ALL = 1;
        INDIVIDUAL = 2;
        GROUP = 4;
        BUILDINFO = 8;
    }
    uint64 courseID = 1;
    int32 type = 2;  // bitwise OR of Type
}
```

Code in `func (db *GormDB) GetAssignmentsWithSubmissions` could be something like:
```golang
m := db.conn.Preload("Submissions").
    Preload("Submissions.Reviews").
    Preload("Submissions.Reviews.GradingBenchmarks").
    Preload("Submissions.Reviews.GradingBenchmarks.Criteria").
    Preload("Submissions.Scores")
if withBuildInfo {
    m.Preload("Submissions.BuildInfo")
}
if err := m.Where(&pb.Assignment{CourseID: courseID}).
    Order("'order'").
    Find(&assignments).Error; err != nil {
    return nil, err
}
```

**Comment by oskargjolga** [comment]
Not sure if a bitfield simplifies this message?
`ag/ag.proto:376:15: The first enum value must be zero in proto3.`
https://stackoverflow.com/questions/26810188/protocol-buffers-and-enums-combinations (first answer)

**Comment by meling** [comment]
Does it help to define the flags like this (with `NONE = 0`):
```proto
message SubmissionsForCourseRequest {
    enum Type {
        NONE = 0;
        ALL = 1;
        INDIVIDUAL = 2;
        GROUP = 4;
        BUILDINFO = 8;
    }
    uint64 courseID = 1;
    int32 type = 2;  // bitwise OR of Type
}
```
That being said. This is a bit of a hack, so maybe it isn't worth it.

If we don't do the bitfield variant, I suggest that we invert the `skipBuildInfo`. That is, let's call it `withBuildInfo`.
