### ISSUE TITLE
A problem with saving a submission's build info into the database

### ISSUE THREAD

**Issue by 0xf8f8ff** [autograde/quickfeed#527]
- A submission that because of some reasons missing a build info cannot be updated in the database
- Some build infos get saved into the database with SubmissionID = 0, the corresponding submissions are then treated as if they had no saved build info => cannot be updated
- `CreateSubmission` database method could really use some extensive logging, as right now it returns the same `RecordNotFound` error in several totally unrelated scenarios

**Comment by meling** [comment]
As for the last item on your list #521 is related. I think our policy is to not log stuff in the database layer, but to return errors. Hence, we could probably return errors with added context using `fmt.Errorf("info about current scenario / context: %w", err)`. Then the receiver of the error can log a more useful error and still check if the error was a `RecordNotFound` using new `errors.Is` or `errors.As` functions; see [this blog](https://go.dev/blog/go1.13-errors).

**Comment by meling** [comment]
This log output seems related to this problem:

```log
2021-08-30T22:40:12.092+0200	[35mDEBUG[0m	web/autograder_service.go:544	GetSubmissionsByCourse: courseID:3  withBuildInfo:true
2021-08-30T22:40:16.703+0200	[35mDEBUG[0m	ci/run_tests.go:48	ci.ExtractResults{results 15 0 {
  "BuildInfo": {
    "BuildDate": "2021-08-30T22:40:16",
    "BuildLog": "*** Preparing for Test Execution ***\n*** Finished Test Setup in 2 seconds ***\n*** Running Tests ***\n  Determining projects to restore...\n   LOG DETAILS REMOVED  Test Run Failed.\nTotal tests: 11\n     Passed: 1\n     Failed: 10\n Total time: 1.4250 Seconds\n*** Finished Running Tests in 15 seconds ***",
    "ExecTime": 19686
  },
  "Scores": [
    {
      "Secret": "hidden",
      "TestName": "InsertTest",
      "Score": 3,
      "MaxScore": 3,
      "Weight": 3
    },
    {
      "Secret": "hidden",
      "TestName": "TestObjectQueue",
      "Score": 1,
      "MaxScore": 3,
      "Weight": 3
    },

[ ... snip ... ]

    {
      "Secret": "hidden",
      "TestName": "TestStringQueue",
      "Score": 1,
      "MaxScore": 3,
      "Weight": 3
    }
  ]
} <nil>}
2021-08-30T22:40:16.703+0200	[35mDEBUG[0m	ci/run_tests.go:96	Fetching most recent submission for assignment 2
2021-08-30T22:40:16.704+0200	[35mDEBUG[0m	ci/run_tests.go:115	Rebuild with no previous submission stored in database
2021-08-30T22:40:16.705+0200	[31mERROR[0m	ci/run_tests.go:133	Failed to add submission to database: record not found
```

**Comment by 0xf8f8ff** [comment]
> As for the last item on your list #521 is related. I think our policy is to not log stuff in the database layer, but to return errors. Hence, we could probably return errors with added context using `fmt.Errorf("info about current scenario / context: %w", err)`. Then the receiver of the error can log a more useful error and still check if the error was a `RecordNotFound` using new `errors.Is` or `errors.As` functions; see [this blog](https://go.dev/blog/go1.13-errors).

Right, I meant "logging" as returning more descriptive errors (that eventually would be logged) instead of RecordNotFound which says nothing about the problem.
